[package]
name = "post-cbindings"
version = "0.1.8"
edition = "2021"


[lib]
name = "post"
crate_type = ["staticlib", "cdylib"]

[dependencies]
eyre = "0.6.8"
log = "0.4.17"
post-rs = { path = "../" }
scrypt-ocl = { path = "../scrypt-ocl" }
simple_logger = "4.1.0"

[build-dependencies]
cbindgen = "*"
