[workspace]
members = [".", "ffi", "scrypt-ocl", "initializer", "profiler"]

[package]
name = "post-rs"
version = "0.2.1"
edition = "2021"

[lib]
name = "post"

[dependencies]
aes = "0.8.2"
# Take a dependency on cipher to enable block-padding feature
# as `aes` doesn't expose it.
cipher = { version = "*", features = ["block-padding"] }
eyre = "0.6.8"
regex = "1.7.1"
itertools = "0.10.5"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
bytemuck = "1.13.0"
serde_with = { version = "2.2.0", features = ["base64"] }

scrypt-jane = { git = "https://github.com/spacemeshos/scrypt-jane-rs", branch = "main" }
blake3 = "1.3.3"
bitvec = "1.0.1"
rayon = "1.6.1"
rand = "0.8.5"
log = "0.4.17"
randomx-rs = { git = "https://github.com/spacemeshos/randomx-rs", rev = "18080c74da8b179a2e99d2eef4e0c0279fd6f75a" }


primitive-types = "0.12.1"
thiserror = "1.0.40"
thread_local = "1.1.7"
env_logger = "0.10.0"
tempfile = "3.3.0"

[dev-dependencies]
criterion = "0.4"
tempfile = "3.3.0"
rand = "0.8.5"
proptest = "1.1.0"

[target.'cfg(not(windows))'.dev-dependencies]
pprof = { version = "0.11.1", features = ["flamegraph", "criterion"] }

[[bench]]
name = "proving"
harness = false

[[bench]]
name = "pow"
harness = false

[[bench]]
name = "verifying"
harness = false

[profile.release-clib]
inherits = "release"
strip = true
lto = true
rpath = true
