[package]
name = "service"
version = "0.1.0"
edition = "2021"

[lib]
name = "post_service"
path = "src/lib.rs"

[dependencies]
post-rs = { path = "../" }
prost = "0.12.1"
tonic = { version = "0.10.0", features = ["tls"] }
tokio = { version = "1.0", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "time",
] }
tokio-stream = { version = "0.1", features = ["net"] }
async-stream = "0.3.5"
log = "0.4.20"
eyre = "0.6.8"
env_logger = "0.10.0"
clap = { version = "4.4.4", features = ["derive"] }
hex = "0.4.3"
mockall = "0.11.4"

[build-dependencies]
tonic-build = "0.10.0"
